USE content_istoq;
CREATE TABLE IF NOT EXISTS accounts(
id VARCHAR(36) NOT NULL PRIMARY KEY,
token VARCHAR(255) NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL
)ENGINE = InnoDB;
