USE content_istoq;
CREATE TABLE IF NOT EXISTS orders(
id VARCHAR(36) NOT NULL PRIMARY KEY,
client VARCHAR(255) NOT NULL,
account_id VARCHAR(36) NOT NULL,
FOREIGN KEY (`account_id`) REFERENCES accounts (`id`) ON DELETE CASCADE ON UPDATE NO ACTION,
product VARCHAR(255) NOT NULL,
quantity VARCHAR (10)  NOT NULL,
price VARCHAR (10) NOT NULL,
discount VARCHAR (5) NOT NULL,
created_at DATETIME NOT NULL
)ENGINE = InnoDB;